CREATE TABLE IF NOT EXISTS ServerConfigs (
    server_id UNSIGNED BIG INT,
    prefix CHAR(8) NOT NULL
);
CREATE TABLE IF NOT EXISTS Users (
    user_id UNSIGNED BIG INT NOT NULL PRIMARY KEY,
    last_daily TIMESTAMP,
    fishes INT NOT NULL DEFAULT 0,
    wealth INT NOT NULL DEFAULT 0,
    shipped_with UNSIGNED BIG INT,
    shipped_since TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Actions (
    actor_id UNSIGNED BIGINT NOT NULL PRIMARY KEY,
    target_id UNSIGNED BIGINT NOT NULL,
    hugs UNSIGNED INT NOT NULL DEFAULT 0,
    kills UNSIGNED INT NOT NULL DEFAULT 0,
    slaps UNSIGNED INT NOT NULL DEFAULT 0,
    kisses UNSIGNED INT NOT NULL DEFAULT 0
);